### ISSUE TITLE
Image artifacts on GPU

### ISSUE THREAD

**Issue by mcahn** [StephanPreibisch/FourierConvolutionCUDALib#25] opened 2017-10-24 15:51 UTC
Hello,

I'm attempting to run Fuse/Deconvolve Dataset. When I run the process on a CPU I get a good image.  When I run on a GPU using FourierConvolutionCUDALib the image contains horizontal stripes.  This happens with all the GPU's and cudatoolkit versions I've tried:

Nvidia K20, cudatoolkit version 7.0 and 8.0
NVidia P100, cudatoolkit versions 8.0 and 9.0

A CPU (good) image and GPU (bad) image are below.

On a side note, with cudatoolkit version 8.0 on the P100, the how_cufft_works test fails.  With 9.0, it works.

Any help would be greatly appreciated.

Best,
Matthew Cahn

**CPU**

![image](https://user-images.githubusercontent.com/3868378/31953442-2c9d7ec8-b8b1-11e7-9d56-f158c609959c.png)

**GPU**

![image](https://user-images.githubusercontent.com/3868378/31953457-3735572a-b8b1-11e7-9b56-8584747cc380.png)

**Comment by mcahn** [comment] 2017-10-25 19:29
I also tried building the library with cudatoolkit 5.5.22 and running it on the K20, which gave a much more garbled image.  And I tried setting the compute capability in CMakeLists.txt to 60 (only) to match the capability of the P100.  That gave the same image artifact as in my posting above.  Still hoping you might have some guidance.

Best,
Matthew

**Comment by psteinb** [comment] 2017-10-26 08:03
hi, thanks for posting the issue. I'll need to see how I can sqeeze it into my schedule. But I'll try to work on it. First off, which convolution mode did you use from the java side? AFAIK, the user can select, "whole image, "256^3", "128^3" etc? I'll try to see if I can get CUDA 9 installed. IIRC, the P100 I have access too might not  have it. I'll have a look at the test case first.

**Comment by mcahn** [comment] 2017-10-26 15:48
Thanks, Peter.  We are using "Whole image".  I'm attaching a PDF document that shows all the settings we're using, in case that helps.  If duplicating the issue there is a problem, getting you an account on our cluster is an option.  Please let me know if there's anything I can do to help.

-- Matthew
[Multiview Deconvolution.pdf](https://github.com/StephanPreibisch/FourierConvolutionCUDALib/files/1419067/Multiview.Deconvolution.pdf)

**Comment by psteinb** [comment] 2017-10-27 14:46
thanks for the document. last piece of information, what snapshot version of `Spim_Registration` did you use? Just search for a file with that name in the fiji directory, it should have the version number in it's filename IIRC. I'll try to come up with some data then and see if I can reproduce this issue on my development box. Or is there any chance you can share your data? Access to your cluster is the other option, if that is painless. For this, please contact me offline.

**Comment by mcahn** [comment] 2017-10-27 17:30
I did a git clone of this:

https://github.com/fiji/SPIM_Registration

although that may not be the plugin I have installed.  I think I installed
the plugin through the Fiji menus, and the Fiji directory has this:

Fiji.app/plugins/SPIM_Registration-5.0.16.jar


For the deconvolution GPU library download and built:

git clone https://github.com/StephanPreibisch/FourierConvolutionCUDALib.git


and for detecting interest points:

git clone https://github.com/StephanPreibisch/SeparableConvolutionCUDALib


Now I've found this for the first time:

https://github.com/PreibischLab/multiview-reconstruction

which seems much newer.  Am I running the wrong code?  None of these
downloaded git repos contains a file named Spim_Registration. The fiji
directory contains:

Fiji.app/plugins/SPIM_Registration-5.0.16.jar


It's easy for me to get you an account.  The only part that can be a
nuisance is that it requires that you connect to our VPN (there's a VPN
client to download), and it uses DUO authentication, so you would have to
install DUO someplace (usually on a smartphone) unless you already use DUO
for something.

I think the data is your or Stephan's demo data.  It's seven files
named img_Angle*.tif.  I can track this down better if needed.

Matthew

**Comment by mcahn** [comment] 2017-11-03 18:03
Hi Peter,
I wondered if you had any futrher thoughts on where we might be going wrong.
Best,
Matthew

**Comment by StephanPreibisch** [comment] 2017-12-02 10:38
Hi, could you post a screenshot of the parameters used for running the plugin? That could be related ...

**Comment by mcahn** [comment] 2017-12-02 22:15
Here are screenshots of the parameters we're using.

Best,
Matthew

[Multiview-Deconvolution.pdf](https://github.com/StephanPreibisch/FourierConvolutionCUDALib/files/1524295/Multiview-Deconvolution.pdf)

**Comment by StephanPreibisch** [comment] 2017-12-10 12:29
Hi, did you try to not use CellImg, but ArrayImg for the ImgLib2 container in the Multiview deconvolution?

**Comment by SternTomer** [comment] 2017-12-11 19:43
Hi, yes, we did try many different combinations of parameters of different types, including this one, and always got that same result. 
I'm attaching another example of the output after running on the entire embryo. It seems to me like there's a part in the algorithm that needs to turn a series of voxels into the 3D array, but doesn't have the correct [X,Y,Z] dimensions of the box, so the distribution of the voxels comes out like this. Does this possibility make any sense?
![demo](https://user-images.githubusercontent.com/26303576/33850362-a0c7a6b6-de81-11e7-8f35-be6a1feda1e8.png)

**Comment by MM603** [comment] 2018-06-01 09:30
Hi
How did you solve this problem?
Cheers,
Mj

**Comment by SternTomer** [comment] 2018-06-01 13:02
Hi,
We used the Multiview-Reconstruction plugin instead of the BigStitcher plugin, until we noticed that we actually need the latter. Once we shifted things started to work, except for when using the "one block" or the "specify maximal block size manually" - in both of these the problem persists.
Tomer

**Comment by StephanPreibisch** [comment] 2018-06-01 14:16
Hi, I really cannot recapitulate this error. Does it only occur when the BigStitcher update site is active?

**Comment by StephanPreibisch** [comment] 2018-06-01 14:17
And only with GPU?

**Comment by MM603** [comment] 2018-06-01 16:23
Hi, No for us the error was occurring only with GPU before installing BigStitcher plugin. And also only on Linux not Windows (we're using a dual boot). 
But thanks a lot for the answer, it is working now with BigStitcher
Cheers

**Comment by SternTomer** [comment] 2018-06-01 18:21
For us the problems with "one block" and "specify maximal block size manually" are when using the GPU. When using CPU for these options it's working fine.

**Comment by StephanPreibisch** [comment] 2018-06-02 09:41
Yes, this makes sense because the block sizes can be quite odd then ... I’ll disable this combination in the GUI. Thanks a lot!

**Comment by StephanPreibisch** [comment] 2018-06-02 10:56
Should be fixed with commit https://github.com/PreibischLab/multiview-reconstruction/commit/bf07c80737866853a3ea9e5aac240fee6891b6af

**Closed as completed by StephanPreibisch** 2018-06-02 10:56 UTC

**Comment by SternTomer** [comment] 2018-06-03 12:45
Thanks.

**Comment by MM603** [comment] 2018-06-05 09:14
Thanks

**Comment by ChristopherMcFaul** [comment] 2018-06-22 01:30
Thank you for this thread! Was scratching my head for a while when I started seeing similar results.
